from pathlib import Path
import click
import logging

from tidetool.lib.tide_generation import generate_tides_from_zdf

def configure_logger():
    logging.basicConfig(level="DEBUG")


configure_logger()


@click.command()
@click.option(
    '-zd', '--zone-definition',
    required=True,
    type=click.Path(
        exists=True,
        file_okay=True,
        dir_okay=False,
        resolve_path=True),
    help=(
        "Path to Zone Definition File (.zdf)"
    )
)
@click.option(
    '-df', '--data-folder',
    required=True,
    type=click.Path(
        exists=True,
        file_okay=False,
        dir_okay=True,
        resolve_path=True),
    help=(
        "Path to root of data folder required by AVISO FES. "
        "This should include a `load_tide` and `ocean_tide` sub folder "
        "including netcdf files, and the config files load_tide.ini "
        "and ocean_tide.ini"
    )
)
@click.option(
    '-y', '--year',
    required=False,
    default=2005,
    type=int,
    help=(
        "Tide data will be generated for this calendar year"
    )
)
@click.option(
    '-tp', '--time-period',
    required=False,
    default=10,
    type=int,
    help=(
        "Time (minutes) in betweeen predicted tide values that will be "
        "included in the tide data files generated by this process."
    )
)
@click.pass_context
def generate_tides(ctx, zone_definition, data_folder, year, time_period):
    """
    Reads an existing zdf file, identifies locations of tide data to be
    predicted and the desired file names, then generates these tide files
    using predicted data.
    """
    if year < 1900 or year >= 2100:
        # really just to catch the case of user giving a two digit year
        # eg; 95 instead of 1995
        raise RuntimeError("Year must be between 1900 and 2100")
    click.echo(f"running on: {zone_definition} for year {year}")

    generate_tides_from_zdf(
        Path(zone_definition),
        Path(data_folder),
        year,
        time_period
    )


@click.group()
@click.option(
    '-e', '--fail-on-error',
    is_flag=True,
    help=(
        "Should parsing errors be treated as warnings and continue, "
        "or fail and exit the application"
    )
)
@click.pass_context
def cli(ctx, fail_on_error):
    ctx.obj['fail_on_error'] = fail_on_error
    pass


cli.add_command(generate_tides)


def main():
    cli(obj={})


if __name__ == '__main__':
    main()
