
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  unit_tests_job:
    runs-on: ubuntu-latest
    name: Run the Tide Tool unit tests
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v3
      - name: Pytest action step
        uses: ./.github/actions/pytest-action.yaml
