# Uses the Dockerfile in the root of this repo to run unit tests
# for the Tide Tool
name: 'Tide Tool application'
description: 'Unit tests for the tide tool application'

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

runs:
  using: 'docker'
  image: 'Dockerfile'
